### ISSUE TITLE
Not work well when specific situation

### ISSUE THREAD

**Issue by patis8s** [stysmmaker/FCurveHandleCopy#1]
Hello, Thank you for creating amazing addon! :) I love Flow and Ease Copy script for after effects. So I was looking for this addon for a long time.
By the way, I found some bugs.
It is difficult to explain. So I uploaded the project file on google drive. Please check :)
https://drive.google.com/drive/folders/1_v4Dy8jDIvWisiZsDt6nr92tTUvDrhce?usp=sharing
Thank you!

**Comment by stysmmaker** [comment]
Thanks for the report! @lachrymaLF has managed to solve this issue in #2 so I'm closing this now. If something pops up again feel free to open another issue. Cheers!
